### ISSUE TITLE
Build error for cpp example?

### ISSUE THREAD

**Issue by sandyhsia** [rvbust/Vis#1]
![build_error](https://user-images.githubusercontent.com/15709515/126888543-cb9099cb-3323-4c6f-85ce-bc85fee53598.png)

In Vis/Examples/C++/Basics.cpp, change the line from 
`auto v = Vis::View("Basics")`
to
`Vis::View v("Basics");` would help.

**Comment by blackball** [comment]
Fixed. Thanks!
