### ISSUE TITLE
PyVis导入问题

### ISSUE THREAD

**Issue by linuxsand** [rvbust/Vis#2]
你们好，我是 Windows 用户，按照 readme 所说执行 `python Setup.py install` 后，跑如下例子失败。

```
from RVBUST import Vis  # No module named 'RVBUST'
v1 = Vis.View("View1", shared = True)
```

使用如下代码是 OK 的：

```
import PyVis as Vis
v1 = Vis.View("View1", shared = True)
```

**Comment by IzumiHoshi** [comment]
你好。感谢您使用我们的sdk。您的使用方式在 Windows 上是正确的。
因为我们这边大部分人使用的都是 linux ，所以例子上的导入方式都是 linux 上的。

**Comment by xiaoniaoyou** [comment]
你好，有这个项目的架构图吗？想结合源码深入了解。

**Comment by xiaoniaoyou** [comment]
![image](https://user-images.githubusercontent.com/8403508/127250716-af07241e-466c-41bc-8467-35d6845e5fbe.png)
请问这个怎么解决？编译Examples/C++的例子。

**Comment by IzumiHoshi** [comment]
> ![image](https://user-images.githubusercontent.com/8403508/127250716-af07241e-466c-41bc-8467-35d6845e5fbe.png)
> 请问这个怎么解决？编译Examples/C++的例子。

你好。感谢您使用我们的sdk。
请提交另外的issue来提出你的问题。 并且在提问中描述一下你使用的系统版本。方便我们分析问题。
