### ISSUE TITLE
Support for pointcloud loading?

### ISSUE THREAD

**Issue by Fang-Haoshu** [rvbust/Vis#3]
Hi dear developpers of rvbust/vis,

Thanks for open-sourcing such a fantastic tool! It helps a lot for our research. 
May I ask that if it supports loading pointcloud data, or if you are planning to do so? Because many of our research will incorporate point cloud information.

Best wishes,
haoshu

**Comment by yuecideng** [comment]
Hi, do you mean loading point cloud data directly from file?  Currently Vis supports point cloud drawing using `Point` of `PyVis.View` object, but the data should be readed into `List` in `python` or `std::vecotr<float>` in `cpp`. You can use some typical 3d processing library to read the point cloud data such as `pcl`, `open3d`.

**Comment by Fang-Haoshu** [comment]
Got it, many thanks!

**Comment by blackball** [comment]
@Fang-Haoshu

https://github.com/rvbust/Vis/blob/1ad2350bb6b434995d298637efd83047f561d4b0/Examples/Python/SegmentPlanes.py#L19

FYI.
