### ISSUE TITLE
编译工程目录下Examples/C++/Basics.cpp报错，找不到头文件。

### ISSUE THREAD

**Issue by xiaoniaoyou** [rvbust/Vis#4]
![image](https://user-images.githubusercontent.com/8403508/127287501-d697fe9c-e192-4573-957a-c69233ed6507.png)

系统是ubuntu20.04。

**Comment by blackball** [comment]
在Docker里面用全新的ubuntu 20.04测试没有问题。需要提供更多的信息方便我们找到问题。谢谢！

**Comment by IzumiHoshi** [comment]
> ![image](https://user-images.githubusercontent.com/8403508/127287501-d697fe9c-e192-4573-957a-c69233ed6507.png)
> 
> 系统是ubuntu20.04。

我看到你编译的目录是在Vis/Examples/C++/build 内，你可以尝试一下在 Vis/build 目录下编译整个工程试试看。

**Comment by blackball** [comment]
应该是编译目录错误导致。
